#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII

xrandr --output DP-3 --mode 1920x1080 --rate 144.00 &
xrandr --output DP-4 --mode 1920x1080 --rate 144.00 &

nitrogen --restore &
dunst -config ~/.config/dunst/dunstrc &
picom --config ~/.config/picom/picom.conf &
setxkbmap -option grp:alt_shift_toggle us,ru &
xsetroot -cursor_name left_ptr &
Thunderbird &
Spotify &
$HOME/.config/polybar/launch.sh --material &


bspc config border_width           2
bspc config window_gap             4
bspc config normal_border_color    "#6272Aa"
bspc config active_border_color    "#BD93F9"
bspc config focused_border_color   "#BD93F9"
bspc config presel_feedback_color  "#6272a4"

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc rule -a Chromium desktop='^2'
bspc rule -a Thunderbird desktop '^3'
bspc rule -a Spotify desktop '^4'
bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off desktop='^1' rectangle=450x1000+24+50
